export const captions = [
    {
        id: 1,
        timestamps: "00:00:45 — 00:03:24",
        text: {
            english: "This was not intended to be remembered",
            french: "Ceci n’était pas destiné à être mémorisé",
            german: "Dies war nicht dazu bestimmt, erinnert zu werden",
            indonesian: "Ini tidak dimaksudkan untuk diingat",
        },
        timeStart: (45 / 60) * 100,
        duration: 1200,
    },
    {
        id: 2,
        timestamps: "00:04:05 — 00:05:38",
        text: {
            english: "They’ve given this various names.",
            french: "On lui a donné plusieurs noms.",
            german: "Man hat dem verschiedene Namen gegeben.",
            indonesian: "Ini telah diberi berbagai nama.",
        },
        timeStart: 4 * 1000 + (5 / 60) * 100,
        duration: 600,
    },
    {
        id: 3,
        timestamps: "00:07:02 — 00:07:38",
        text: {
            english: "You are looking for clarity.",
            french: "Tu cherches la clarté.",
            german: "Du suchst nach Klarheit.",
            indonesian: "Kamu sedang mencari kejelasan.",
        },
        timeStart: 7 * 1000 + (2 / 60) * 100,
        duration: 400,
    },
    {
        id: 4,
        timestamps: "00:07:39 — 00:07:55",
        text: {
            english: "This may not be important.",
            french: "Ce n’est peut-être pas important.",
            german: "Das ist vielleicht nicht wichtig.",
            indonesian: "Ini mungkin tidak penting.",
        },
        timeStart: 7 * 1000 + (39 / 60) * 100,
        duration: 1200,
    },
    {
        id: 5,
        timestamps: "00:07:56 — 00:09:01",
        text: {
            english: "You are moving too fast.",
            french: "Tu vas trop vite.",
            german: "Du bewegst dich zu schnell.",
            indonesian: "Kamu bergerak terlalu cepat.",
        },
        timeStart: 7 * 1000 + (56 / 60) * 100,
        duration: 1200,
    },
    {
        id: 6,
        timestamps: "00:09:53 — 00:11:49",
        text: {
            english: "Stillness is often mistaken for depth.",
            french: "L’immobilité est souvent confondue avec la profondeur.",
            german: "Stille wird oft mit Tiefe verwechselt.",
            indonesian: "Diam sering disalahartikan sebagai kedalaman.",
        },
        timeStart: 9 * 1000 + (53 / 60) * 100,
        duration: 1200,
    },
    {
        id: 7,
        timestamps: "00:15:07 — 00:16:00",
        text: {
            english: "This has already occured.",
            french: "Ceci s’est déjà produit.",
            german: "Dies ist bereits geschehen.",
            indonesian: "Ini sudah terjadi.",
        },
        timeStart: 15 * 1000 + (7 / 60) * 100,
        duration: 1200,
    },
    {
        id: 8,
        timestamps: "00:19:00 — 00:20:59",
        text: {
            english: "00:19-00.21 (time dilates)",
            french: "00:19-00.21 (le temps se dilate)",
            german: "00:19-00.21 (die Zeit dehnt sich)",
            indonesian: "00:19-00.21 (waktu melambat)",
        },
        timeStart: 19 * 1000,
        duration: 1200,
    },
    {
        id: 9,
        timestamps: "00:23:29 — 00:25:03",
        text: {
            english: "[something changes off-screen]",
            french: "[quelque chose change hors champ]",
            german: "[etwas verändert sich außerhalb des Bildes]",
            indonesian: "[sesuatu berubah di luar layar]",
        },
        timeStart: 23 * 1000 + (29 / 60) * 100,
        duration: 1200,
    },
    {
        id: 10,
        timestamps: "00:26:14 — 00:28:44",
        text: {
            english: '"Are you talking to yourself?"',
            french: "« Tu te parles à toi-même ? »",
            german: "„Redest du mit dir selbst?“",
            indonesian: '"Apakah kamu bicara sendiri?"',
        },
        timeStart: 26 * 1000 + (14 / 60) * 100,
        duration: 1200,
    },
    {
        id: 11,
        timestamps: "00:31:00 — 00:31:15",
        text: {
            english: "ths sctn hs bn rdc",
            french: "ctt sctn a été rdgée",
            german: "dsr abschntt wrd geschwrzt",
            indonesian: "bgn ini tlh disnsor",
        },
        timeStart: 31 * 1000,
        duration: 1200,
    },
    {
        id: 12,
        timestamps: "00:34:15 — 00:36:53",
        text: {
            english: "what were we?",
            french: "qu’étions-nous ?",
            german: "was waren wir?",
            indonesian: "apa kita dulu?",
        },
        timeStart: 34 * 1000 + (15 / 60) * 100,
        duration: 1200,
    },
    {
        id: 13,
        timestamps: "00:40:00 — 00:41:51",
        text: {
            english: "Some shot lingers too long.",
            french: "Un plan s’attarde trop longtemps.",
            german: "Eine Einstellung verweilt zu lange.",
            indonesian: "Satu adegan bertahan terlalu lama.",
        },
        timeStart: 40 * 1000,
        duration: 1200,
    },
    {
        id: 14,
        timestamps: "00:43:20 — 00:45:59",
        text: {
            english: "You are waiting for something to happen.",
            french: "Tu attends que quelque chose se passe.",
            german: "Du wartest darauf, dass etwas geschieht.",
            indonesian: "Kamu menunggu sesuatu terjadi.",
        },
        timeStart: 43 * 1000 + (20 / 60) * 100,
        duration: 1200,
    },
    {
        id: 15,
        timestamps: "00:50:57 — 00:53:59",
        text: {
            english: "A portrait video rotated landscape.",
            french: "Une vidéo portrait tournée en paysage.",
            german: "Ein Hochformatvideo, ins Querformat gedreht.",
            indonesian: "Video potret yang diputar menjadi lanskap.",
        },
        timeStart: 50 * 1000 + (57 / 60) * 100,
        duration: 1200,
    },
    {
        id: 16,
        timestamps: "00:55:53 — 00:56:29",
        text: {
            english: "IMG_2392.MOV is playing.",
            french: "IMG_2392.MOV est en lecture.",
            german: "IMG_2392.MOV wird abgespielt.",
            indonesian: "IMG_2392.MOV sedang diputar.",
        },
        timeStart: 55 * 1000 + (53 / 60) * 100,
        duration: 1200,
    },
    {
        id: 17,
        timestamps: "00:56:30 — 00:58:19",
        text: {
            english: "IMG_4656.MOV is playing.",
            french: "IMG_4656.MOV est en lecture.",
            german: "IMG_4656.MOV wird abgespielt.",
            indonesian: "IMG_4656.MOV sedang diputar.",
        },
        timeStart: 56 * 1000 + (30 / 60) * 100,
        duration: 1200,
    },
    {
        id: 18,
        timestamps: "01:07:43 — 01:08:40",
        text: {
            english: "This was demolished in 2021.",
            french: "Ceci a été démoli en 2021.",
            german: "Dies wurde 2021 abgerissen.",
            indonesian: "Ini dirobohkan pada tahun 2021.",
        },
        timeStart: 1 * 60 * 1000 + 7 * 1000 + (43 / 60) * 100,
        duration: 1200,
    },
    {
        id: 19,
        timestamps: "01:17:35 — 01:18:59",
        text: {
            english: "Are you still willing?",
            french: "Es-tu toujours prêt(e) ?",
            german: "Bist du noch bereit?",
            indonesian: "Apakah kamu masih bersedia?",
        },
        timeStart: 1 * 60 * 1000 + 17 * 1000 + (35 / 60) * 100,
        duration: 1200,
    },
    {
        id: 20,
        timestamps: "01:22:44 — 01:24:19",
        text: {
            english: "This was about 5,500km from here.",
            french: "C’était à environ 5 500 km d’ici.",
            german: "Das war etwa 5.500 km von hier entfernt.",
            indonesian: "Ini sekitar 5.500 km dari sini.",
        },
        timeStart: 1 * 60 * 1000 + 22 * 1000 + (44 / 60) * 100,
        duration: 1200,
    },
    {
        id: 21,
        timestamps: "01:24:20 — 01:26:20",
        text: {
            english: "Prayer for all beings.",
            french: "Prière pour tous les êtres.",
            german: "Gebet für alle Wesen.",
            indonesian: "Doa untuk semua makhluk.",
        },
        timeStart: 1 * 60 * 1000 + 24 * 1000 + (20 / 60) * 100,
        duration: 1200,
    },
    {
        id: 22,
        timestamps: "01:29:10 — 01:30:34",
        text: {
            english: "[silence continues]",
            french: "[le silence continue]",
            german: "[die Stille hält an]",
            indonesian: "[keheningan berlanjut]",
        },
        timeStart: 1 * 60 * 1000 + 29 * 1000 + (10 / 60) * 100,
        duration: 1200,
    },
    {
        id: 23,
        timestamps: "01:37:47 — 01:38:42",
        text: {
            english: "Year of the ocean...",
            french: "Année de l’océan...",
            german: "Jahr des Ozeans...",
            indonesian: "Tahun laut...",
        },
        timeStart: 1 * 60 * 1000 + 37 * 1000 + (47 / 60) * 100,
        duration: 1200,
    },
    {
        id: 24,
        timestamps: "01:38:43 — 01:40:27",
        text: {
            english: "I remember there was a hill behind.",
            french: "Je me souviens qu’il y avait une colline derrière.",
            german: "Ich erinnere mich, dass dahinter ein Hügel war.",
            indonesian: "Aku ingat dulu ada bukit di belakang.",
        },
        timeStart: 1 * 60 * 1000 + 38 * 1000 + (43 / 60) * 100,
        duration: 1200,
    },
    {
        id: 25,
        timestamps: "01:46:41 — 01:48:27",
        text: {
            english: "[seen]",
            french: "[vu]",
            german: "[gesehen]",
            indonesian: "[terlihat]",
        },
        timeStart: 1 * 60 * 1000 + 46 * 1000 + (41 / 60) * 100,
        duration: 1200,
    },
];
export const captionsLoop2 = [
    {
        id: 1,
        timestamps: "00:00:45 — 00:03:05",
        text: {
            english: "This has already occured.",
            french: "Ceci s’est déjà produit.",
            german: "Dies ist bereits geschehen.",
            indonesian: "Ini sudah terjadi.",
        },
        timeStart: (45 / 60) * 100,
        duration: 1200,
    },
    {
        id: 2,
        timestamps: "00:03:46 — 00:05:24",
        text: {
            english: "You remembered it anyway",
            french: "Tu t’en es souvenu quand même",
            german: "Du hast dich trotzdem daran erinnert",
            indonesian: "Kamu tetap mengingatnya",
        },
        timeStart: 4 * 1000 + (5 / 60) * 100,
        duration: 600,
    },
    {
        id: 3,
        timestamps: "00:06:33 — 00:07:44",
        text: {
            english: "You are still looking for clarity.",
            french: "Tu cherches encore la clarté.",
            german: "Du suchst immer noch nach Klarheit.",
            indonesian: "Kamu masih mencari kejelasan.",
        },
        timeStart: 7 * 1000 + (2 / 60) * 100,
        duration: 400,
    },
    {
        id: 4,
        timestamps: "00:07:48 — 00:08:50",
        text: {
            english: "This may not be important.",
            french: "Ce n’est peut-être pas important.",
            german: "Das ist vielleicht nicht wichtig.",
            indonesian: "Ini mungkin tidak penting.",
        },
        timeStart: 7 * 1000 + (39 / 60) * 100,
        duration: 1200,
    },
    {
        id: 5,
        timestamps: "00:09:53 — 00:11:49",
        text: {
            english: "Stillness is often mistaken for depth.",
            french: "L’immobilité est souvent confondue avec la profondeur.",
            german: "Stille wird oft mit Tiefe verwechselt.",
            indonesian: "Diam sering disalahartikan sebagai kedalaman.",
        },
        timeStart: 7 * 1000 + (56 / 60) * 100,
        duration: 1200,
    },
    {
        id: 6,
        timestamps: "00:15:07 — 00:16:00",
        text: {
            english: "xx px/s",
            french: "xx px/s",
            german: "xx px/s",
            indonesian: "xx px/s",
        },
        timeStart: 9 * 1000 + (53 / 60) * 100,
        duration: 1200,
    },
    {
        id: 7,
        timestamps: "00:19:00 — 00:20:59",
        text: {
            english: "(time dilates)",
            french: "(le temps se dilate)",
            german: "(die Zeit dehnt sich)",
            indonesian: "(waktu melambat)",
        },
        timeStart: 15 * 1000 + (7 / 60) * 100,
        duration: 1200,
    },
    {
        id: 8,
        timestamps: "00:23:29 — 00:25:03",
        text: {
            english: "[something changes off-screen]",
            french: "[quelque chose change hors champ]",
            german: "[etwas verändert sich außerhalb des Bildes]",
            indonesian: "[sesuatu berubah di luar layar]",
        },
        timeStart: 19 * 1000,
        duration: 1200,
    },
    {
        id: 9,
        timestamps: "00:26:14 — 00:28:44",
        text: {
            english: '"Are you talking to yourself?"',
            french: "« Tu te parles à toi-même ? »",
            german: "„Redest du mit dir selbst?“",
            indonesian: '"Apakah kamu bicara sendiri?"',
        },
        timeStart: 23 * 1000 + (29 / 60) * 100,
        duration: 1200,
    },
    {
        id: 10,
        timestamps: "00:31:00 — 00:31:15",
        text: {
            english: "ths sctn hs bn rdc",
            french: "ctt sctn a été rdgée",
            german: "dsr abschntt wrd geschwrzt",
            indonesian: "bgn ini tlh disnsor",
        },
        timeStart: 26 * 1000 + (14 / 60) * 100,
        duration: 1200,
    },
    {
        id: 13,
        timestamps: "00:34:15 — 00:36:53",
        text: {
            english: "what were we?",
            french: "qu’étions-nous ?",
            german: "was waren wir?",
            indonesian: "apa kita dulu?",
        },
        timeStart: 34 * 1000 + (15 / 60) * 100,
        duration: 1200,
    },
    {
        id: 14,
        timestamps: "00:40:00 — 00:41:51",
        text: {
            english: "Some shot lingers too long.",
            french: "Un plan s’attarde trop longtemps.",
            german: "Eine Einstellung verweilt zu lange.",
            indonesian: "Satu adegan bertahan terlalu lama.",
        },
        timeStart: 40 * 1000,
        duration: 1200,
    },
    {
        id: 15,
        timestamps: "00:43:20 — 00:45:19",
        text: {
            english: "Something may have already happened.",
            french: "Quelque chose s’est peut-être déjà produit.",
            german: "Etwas ist vielleicht schon geschehen.",
            indonesian: "Sesuatu mungkin sudah terjadi.",
        },
        timeStart: 43 * 1000 + (20 / 60) * 100,
        duration: 1200,
    },
    {
        id: 16,
        timestamps: "00:50:57 — 00:53:45",
        text: {
            english: ">> time stamp",
            french: ">> horodatage",
            german: ">> Zeitstempel",
            indonesian: ">> stempel waktu",
        },
        timeStart: 50 * 1000 + (57 / 60) * 100,
        duration: 1200,
    },
    {
        id: 17,
        timestamps: "00:55:53 — 00:56:29",
        text: {
            english: "IMG_2392.MOV is playing.",
            french: "IMG_2392.MOV est en lecture.",
            german: "IMG_2392.MOV wird abgespielt.",
            indonesian: "IMG_2392.MOV sedang diputar.",
        },
        timeStart: 55 * 1000 + (53 / 60) * 100,
        duration: 1200,
    },
    {
        id: 18,
        timestamps: "00:56:30 — 00:58:19",
        text: {
            english: "IMG_4656.MOV is playing.",
            french: "IMG_4656.MOV est en lecture.",
            german: "IMG_4656.MOV wird abgespielt.",
            indonesian: "IMG_4656.MOV sedang diputar.",
        },
        timeStart: 56 * 1000 + (30 / 60) * 100,
        duration: 1200,
    },
    {
        id: 19,
        timestamps: "01:07:43 — 01:08:40",
        text: {
            english: "This was demolished in 2021.",
            french: "Ceci a été démoli en 2021.",
            german: "Dies wurde 2021 abgerissen.",
            indonesian: "Ini dirobohkan pada tahun 2021.",
        },
        timeStart: 1 * 60 * 1000 + 7 * 1000 + (43 / 60) * 100,
        duration: 1200,
    },
    {
        id: 20,
        timestamps: "01:17:35 — 01:18:59",
        text: {
            english: "Are you still willing?",
            french: "Es-tu toujours prêt(e) ?",
            german: "Bist du noch bereit?",
            indonesian: "Apakah kamu masih bersedia?",
        },
        timeStart: 1 * 60 * 1000 + 17 * 1000 + (35 / 60) * 100,
        duration: 1200,
    },
    {
        id: 21,
        timestamps: "01:21:15 — 01:22:43",
        text: {
            english: "How’s this relevant here?",
            french: "En quoi est-ce pertinent ici ?",
            german: "Was hat das hiermit zu tun?",
            indonesian: "Apa relevansinya di sini?",
        },
        timeStart: 1 * 60 * 1000 + 22 * 1000 + (44 / 60) * 100,
        duration: 1200,
    },
    {
        id: 22,
        timestamps: "01:24:20 — 01:26:20",
        text: {
            english: "Prayer for all beings.",
            french: "Prière pour tous les êtres.",
            german: "Gebet für alle Wesen.",
            indonesian: "Doa untuk semua makhluk.",
        },
        timeStart: 1 * 60 * 1000 + 24 * 1000 + (20 / 60) * 100,
        duration: 1200,
    },
    {
        id: 23,
        timestamps: "01:29:10 — 01:30:34",
        text: {
            english: "[silence continues]",
            french: "[le silence continue]",
            german: "[die Stille hält an]",
            indonesian: "[keheningan berlanjut]",
        },
        timeStart: 1 * 60 * 1000 + 29 * 1000 + (10 / 60) * 100,
        duration: 1200,
    },
    {
        id: 24,
        timestamps: "01:37:47 — 01:38:42",
        text: {
            english: "Year of the ocean...",
            french: "Année de l’océan...",
            german: "Jahr des Ozeans...",
            indonesian: "Tahun laut...",
        },
        timeStart: 1 * 60 * 1000 + 37 * 1000 + (47 / 60) * 100,
        duration: 1200,
    },
    {
        id: 25,
        timestamps: "01:38:43 — 01:40:27",
        text: {
            english: ">> activity",
            french: ">> activité",
            german: ">> Aktivität",
            indonesian: ">> aktivitas",
        },
        timeStart: 1 * 60 * 1000 + 38 * 1000 + (43 / 60) * 100,
        duration: 1200,
    },
    {
        id: 26,
        timestamps: "01:45:38 — 01:48:27",
        text: {
            english: "You have already seen this.",
            french: "Tu as déjà vu ceci.",
            german: "Du hast das schon gesehen.",
            indonesian: "Kamu sudah melihat ini sebelumnya.",
        },
        timeStart: 1 * 60 * 1000 + 46 * 1000 + (41 / 60) * 100,
        duration: 1200,
    },
];
export const customCaptions = [
    {
        id: 5,
        text: {
            english: "You're moving too fast",
            french: "Tu vas trop vite",
            german: "Du bewegst dich zu schnell",
            indonesian: "Kamu bergerak terlalu cepat",
        },
        condition: (state) => state.speed > 6,
        duration: 1000,
    },
    {
        id: 6,
        text: {
            english: "Wait, don't leave",
            french: "Attends, ne pars pas",
            german: "Warte, geh nicht",
            indonesian: "Tunggu, jangan pergi",
        },
        condition: (state) => state.position.y < 100 && state.directionY === "up",
        duration: 1000,
    },
];
